#!/usr/bin/env bash

# Initialize variables with default values
themeName=""
sourceDir="${HOME}/.config/alacritty/themes/"
terminalWidth=$(tput cols)

# Use getopts to process flags
while getopts ':s:l' opt; do
    case "$opt" in
    s)
        # Set the 'themeName' variable to the value of the -s flag argument
        themeName="$OPTARG"

        # Check if the input is empty
        if [ -z "$themeName" ]; then
            echo "Usage: $0 -s themeName (no .yml extension)"
            exit 1
        fi

        # Build the full source and destination paths
        sourcePath="${sourceDir}${themeName}.yml"
        destinationPath="${HOME}/.config/alacritty/activeTheme.yml"

        # Check if the source file exists
        if [ ! -e "$sourcePath" ]; then
            echo "Input file not found: $sourcePath"
            exit 1
        fi

        # Perform the copy operation
        cp "$sourcePath" "$destinationPath"

        echo "Changed theme to $themeName"
        exit 0
        ;;

    l)
        echo "Path to themes: $sourceDir"
        # find "$sourceDir" -type f -name "*.yml" -exec sh -c 'basename "$0" .yml' {} \;
        ls "$sourceDir"*.yml | xargs -I {} basename {} .yml | column -x -c $terminalWidth
	exit 0  # Exit after listing files, no need to continue
        ;;

    # Handle unknown options
    \?)
        echo "Invalid option: -$OPTARG" >&2
        exit 1
        ;;

    # -s requires an argument
    :)
        echo "Option -$OPTARG requires an argument." >&2
        exit 1
        ;;
    esac
done

# If we reach here, it means no valid flags were provided as arguments
echo "Usage: $0 [-s themeName] [-l]"
exit 1
